name: alpata_assignment
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  shared_preferences: ^2.0.15
  uuid: ^3.0.6
  auto_route: ^5.0.1
  auto_route_generator: ^5.0.2
  build_runner: ^2.2.0
  provider: ^6.0.3
  fluttertoast: ^8.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/
